apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: test-app-k8s
spec:
  selector:
    matchLabels:
      app: test-app-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: test-app-k8s
    spec:
      containers:
        - name: test-app-k8s
          image: ajeet9415/javaappjdk17:01 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the clustertes


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: test-app-k8s-svc
spec:
  selector:
    app: test-app-k8s
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 9090 # The port exposed by the service
  type: NodePort # type of the service.